name: Scrape and Sum

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright
        run: npm install

      - name: Run Sum Script (24f2000689@ds.study.iitm.ac.in)
        run: npm start
